#!/usr/bin/env python

import os
import sys

import gentoopm

sys.path.append('lib')
import profilewalker

pm = gentoopm.get_package_manager()
r = pm.repositories['gentoo']


class ObsoletePackageScanner(profilewalker.ProfileVisitor):
	def handle_pkg(self, fn, pkg, path):
		if pkg.startswith('-'):
			pkg = pkg[1:]
		if pkg not in r:
			print('%s : %s' % (os.path.relpath(path, r.path), pkg))


p = ObsoletePackageScanner()

for dirpath, dirnames, filenames in os.walk(os.path.join(r.path, 'profiles')):
	profilewalker.process_profile(dirpath, p, verbose=False, recursive=False)
