#!/usr/bin/env python

import os
import sys

import gentoopm

sys.path.append('lib')
import profilewalker

pm = gentoopm.get_package_manager()
r = pm.repositories['gentoo']


all_flags = set()
# add arch flags
with open(os.path.join(r.path, 'profiles', 'arch.list'), 'r', encoding='utf8') as f:
	for l in f:
		if l.startswith('#') or not l.strip():
			continue
		l = l.strip()
		all_flags.add(l)
for p in r:
	all_flags |= p.use


class ObsoleteUseScanner(profilewalker.ProfileVisitor):
	def handle_use(self, fn, f, path):
		if f.startswith('-'):
			f = f[1:]

		if f not in all_flags:
			print('%s : %s' % (os.path.relpath(path, r.path), f))


p = ObsoleteUseScanner()

for dirpath, dirnames, filenames in os.walk(os.path.join(r.path, 'profiles')):
	profilewalker.process_profile(dirpath, p, verbose=False, recursive=False)
