#!/usr/bin/env python

import os

import gentoopm

pm = gentoopm.get_package_manager()
r = pm.repositories['gentoo']


def process_file(fp):
	with open(fp, 'r', encoding='utf8') as f:
		for l in f:
			if l.startswith('#') or not l.strip():
				continue
			pkg, *flags = l.strip().split()
			if pkg[0] == '-':
				pkg = pkg[1:]

			for f in flags:
				for p in r.filter(pkg):
					if f.lstrip('+-') in p.use:
						break
				else: # not found or no packages match
					print('%s : %s %s' % (os.path.relpath(fp, r.path), pkg, f))


for dirpath, dirnames, filenames in os.walk(os.path.join(r.path, 'profiles')):
	for f in ('package.use', 'package.use.mask', 'package.use.force', 'package.use.stable.mask', 'package.use.stable.force'):
		if f in filenames:
			process_file(os.path.join(dirpath, f))
