#!/usr/bin/env python

import os

import gentoopm

pm = gentoopm.get_package_manager()
r = pm.repositories['gentoo']


def process_file(fp):
	with open(fp, 'r', encoding='utf8') as f:
		for l in f:
			if l.startswith('#') or not l.strip():
				continue
			pkg = l.strip()
			if pkg[0] == '-':
				pkg = pkg[1:]

			if pkg not in r:
				print('%s : %s' % (os.path.relpath(fp, r.path), pkg))


for dirpath, dirnames, filenames in os.walk(os.path.join(r.path, 'profiles')):
	for f in ('package.mask', 'package.unmask'):
		if f in filenames:
			process_file(os.path.join(dirpath, f))
