#!/usr/bin/env python

import os
import sys

import gentoopm

sys.path.append('lib')
import profilewalker

pm = gentoopm.get_package_manager()
r = pm.repositories['gentoo']


class ObsoletePackageUseScanner(profilewalker.ProfileVisitor):
	def handle_pkg_use(self, fn, pkg, f, path):
		for p in r.filter(pkg):
			if f.lstrip('+-') in p.use:
				break
		else: # not found or no packages match
			print('%s : %s %s' % (os.path.relpath(path, r.path), pkg, f))


p = ObsoletePackageUseScanner()

for dirpath, dirnames, filenames in os.walk(os.path.join(r.path, 'profiles')):
	profilewalker.process_profile(dirpath, p, verbose=False, recursive=False)
