#!/usr/bin/env python

import errno
import os
import os.path
import sys

sys.path.append('lib')
import profilewalker


def main(profile_path, output_dir):
	try:
		os.makedirs(output_dir)
	except OSError as e:
		if e.errno != errno.EEXIST:
			raise

	p = profilewalker.CombinedProfile()
	profilewalker.process_profile(profile_path, p)
	p.dump_all(output_dir)

	return 0


if __name__ == '__main__':
	sys.exit(main(*sys.argv[1:]))
