#!/usr/bin/env python

import errno
import os
import os.path
import sys

import gentoopm

sys.path.append('lib')
import profilewalker


pm = gentoopm.get_package_manager()
r = pm.repositories['gentoo']


def main(output_dir):
	top_path = os.path.join(r.path, 'profiles')
	for dirpath, dirnames, filenames in os.walk(top_path):
		if 'parent' in filenames:
			outpath = os.path.join(output_dir, os.path.relpath(dirpath, top_path))
			try:
				os.makedirs(outpath)
			except OSError as e:
				if e.errno != errno.EEXIST:
					raise

			print(dirpath)
			p = profilewalker.CombinedProfile()
			profilewalker.process_profile(dirpath, p, verbose=False)
			p.dump_all(outpath)

	return 0


if __name__ == '__main__':
	sys.exit(main(*sys.argv[1:]))
